version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
    links:
      - sqlite
    ports:
      - 3000:3000



  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite/data
    environment:
      - SQLITE_USER=root
      - SQLITE_PASSWORD=root
      - SQLITE_DB=admin
    ports:
      - 5432:5432

